Feature
akuutsang/Etch-A-Sketch pull request #1
Opened 2023-01-21 09:44 UTC by akuutsang

2023-01-24 10:09 UTC, DanSam5K requested changes
## Hi @akuutsang, ♻️Changes Required♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![ ](https://user-images.githubusercontent.com/64173189/128109485-382fcc99-cf3c-4534-a70a-51351dfd9b39.gif)

## Required Changes ♻️
_Check the comments under the review._

You can also consider:
- Adding a proper README documentation to your project before requesting a Re-review. Kindly checkout this [template](https://github.com/othneildrew/Best-README-Template)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._Hi @akuutsang , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![ ](https://user-images.githubusercontent.com/64173189/128109485-382fcc99-cf3c-4534-a70a-51351dfd9b39.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 10:09 UTC, DanSam5K commented on New/index.css
> +}
- Since writing CSS code with good style guide in mind is a habit that sales a developer, how about you introduced some style guide to help, came across this article [5 things to consider](https://blog.logrocket.com/5-things-to-consider-when-creating-your-css-style-guide-7b85fa70039d/#:~:text=A%20CSS%20style%20guide%20is,more%20consistent%20and%20maintainable%20project.) how about looking it up and see if you can change one or two, what you think? 😉

2023-01-24 10:09 UTC, DanSam5K commented on New/stylesheet.js
> +
- What do you if we can make the white space consistent, when separating code? 🤔

2023-01-24 10:09 UTC, DanSam5K commented on New/stylesheet.js
> +}
- You may consider checking the indentation and white space here also.

2023-01-31 06:09 UTC, akuutsang commented on New/index.css
> +}
ok sir, i will work on it and improve.

2023-01-31 06:10 UTC, akuutsang commented on New/stylesheet.js
> +
Okay, proper indentation. i will be more careful in future projects

2023-01-31 06:10 UTC, akuutsang commented on New/stylesheet.js
> +}
okay

2023-02-05 20:31 UTC, DanSam5K reviewed
Kindly add a README @akuutsang and request for REVIEW.

2023-02-05 20:38 UTC, merged

2023-02-05 20:38 UTC, akuutsang commented
> 

ok sir, thank you for your time and your guidance

2023-02-06 09:39 UTC, akuutsang commented
Good morning sir,
my README file is updated and  ready for review.
thank you and a have a great day!


On Sun, Feb 5, 2023 at 9:31 PM Daniel Samuel ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Kindly commit add the Readme @akuutsang <https://github.com/akuutsang>
> and request for REVIEW.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/akuutsang/Etch-A-Sketch/pull/1#pullrequestreview-1284344747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXLLI3YDB3OUAVSAXGPTP6LWWAE3PANCNFSM6AAAAAAUCJ2SK4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>